version: '3.3'
services:
  web:
    build: 
      context: ./php
      dockerfile: Dockerfile
    container_name: devphp74
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: mysqlB
    image:  mysql:8.0
    command:  --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  root
      MYSQL_DATABASE: test_deb
      MYSQL_USER: diego
      MYSQL_PASSWORD: devpass
    ports:
      - 6033:3306
  

